Metrics Web-app: Project Development
forLoop94/Population-Metrics-App pull request #7
Opened 2023-06-28 15:43 UTC by forLoop94

1. The project is a single-page application (SPA) built with React and Redux.
2. The data retrieved from the API(Rest Countries API) is stored in the Redux store.
3. I filtered the data that I retrieved from the API using a Filter stateless component.
4. Every page (the main page and the pages for each item) have a unique route within the SPA.
5. The project was deployed using [GitHub Pages](https://pages.github.com/).
6. I have added a link to the online version of the app to the README file.
7. I recorded a walkthrough video for the App on Loom  [Walkthrough video](https://www.loom.com/share/8bdac0acc77447f285cdb52bf6464436)

2023-06-28 21:01 UTC, algerina requested changes
Hi @forLoop94 ,

Great job so far! 
- Your App looks awesome however you have a minor issue to fix.

May I highlight the following: 
- [x] Your project looks good 👏  ✔️ 
- [x] You followed the design and everything is almost working properly👏  ✔️ 



## STATUS: CHANGES REQUIRED ♻️ 
PLEASE: check the comments under the review

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-06-28 21:01 UTC, algerina commented on src/App.js
> +      </div>
- [ ] Well done working on the project but your home page is not displayed properly, when we open the app we have an empty page with the Navbar. Kindly fix the issue.


<img width="1178" alt="Screenshot 2023-06-28 at 9 50 47 PM" src="https://github.com/forLoop94/Population-Metrics-App/assets/53347966/c64fa489-84e1-44d2-959d-f746aeaa1c1b">

2023-06-28 21:01 UTC, algerina commented on src/_tests_/Home.test.js
> +  );
- [ Optional] You did well trying to test the Navbar and the home page however it will be more professional to test other components.

2023-06-30 19:44 UTC, codecaiine requested changes
Hi @forLoop94 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good requested changes implementation ✔️ 
- Good UI design set up ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] I would strongly recommend you pay attention to the project requirement for this project you were supposed to use gitflow not github flow. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 19:44 UTC, codecaiine commented on src/App.css
> +* {
- [ ] Good job so far your app is impressive :clap:  But you need to work on your app design. From the project requirement, you should follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) including Typography: font face, size, and weight and Layout: composition and space between elements. You can check the screenshots below :arrow_down: to see the differences. As a developer you need to pay attention to details :+1: 

#### Expected design
![metrics_app(1)](https://user-images.githubusercontent.com/6615394/211091065-a58853ea-2005-4742-8b15-a532f6322253.jpg)
 
#### Your design
![metricss](https://github.com/forLoop94/Population-Metrics-App/assets/6615394/6a0787e1-bb63-4f0d-ba1c-e193146d2cbf)

2023-07-01 10:11 UTC, merged

2023-07-01 10:57 UTC, arslanbisharat commented
Hi @forLoop94,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._